shop/templates/layout-my-account.html
shop/templates/partials/my-account-menu.html
shop/templates/users/addresses.html
shop/user/models.py
shop/user/views.py

Add view to list addresses

---

shop/public/models.py
shop/public/views.py
shop/templates/layout-my-account.html
shop/templates/users/address-form.html
shop/templates/users/addresses.html
shop/user/forms.py
shop/user/models.py
shop/user/views.py

User can now add new addresses

---

requirements/prod.txt
shop/app.py
shop/cart/__init__.py
shop/cart/forms.py
shop/cart/models.py
shop/cart/views.py
shop/extensions.py
shop/fulfilio.py
shop/globals.py
shop/settings.py
shop/templates/cart/cart.html
shop/templates/product/product.html

Add cart functionality

---

shop/templates/layout-my-account.html
shop/templates/public/reset-password.html
shop/templates/users/change-password.html
shop/templates/utils.html
shop/user/forms.py
shop/user/views.py

Shopper should be able to change password from account area

---

shop/app.py
shop/cms/models.py
shop/cms/views.py
shop/templates/cms/pages.html
shop/templates/partials/nav.html

Shopper should be able to view articles (like about-us) on the site

---

shop/public/views.py
shop/templates/partials/search-box.html
shop/templates/public/search.html

Users can now search for products

---

bower.json
manage.py
shop/app.py
shop/cart/forms.py
shop/cart/models.py
shop/cart/views.py
shop/checkout/forms.py
shop/checkout/models.py
shop/checkout/views.py
shop/cms/models.py
shop/cms/views.py
shop/fulfilio.py
shop/node/models.py
shop/node/views.py
shop/product/models.py
shop/product/views.py
shop/public/forms.py
shop/public/models.py
shop/public/views.py
shop/templates/layout.html
shop/templates/product/product.html
shop/user/forms.py
shop/user/models.py
shop/user/views.py
tests/conftest.py
tests/factories.py
tests/test_functional.py
tests/test_models.py

Add provision to allow user to add select variation of product

---

shop/cart/models.py
shop/cart/views.py
shop/checkout/views.py
shop/static/css/style.css
shop/templates/cart/order-confirmation.html

Order confirmation

---

shop/checkout/views.py
shop/public/views.py
shop/templates/checkout/signin-email-in-use.html
shop/templates/emails/layout.html
shop/templates/emails/magic-login-html.html
shop/templates/emails/magic-login-text.txt
shop/user/models.py

Provision to login using token sent in email

---

shop/cart/models.py
shop/static/css/style.css
shop/templates/layout-my-account.html
shop/templates/users/orders.html
shop/user/models.py
shop/user/views.py

User orders page with filter

---

shop/app.py
shop/cms/models.py
shop/cms/views.py
shop/filters.py
shop/globals.py
shop/node/models.py
shop/product/models.py
shop/settings.py
shop/templates/cart/order-confirmation.html
shop/templates/cms/category.html
shop/templates/footer.html
shop/templates/layout.html
shop/templates/node/node.html
shop/templates/partials/nav.html
shop/templates/product/shop.html
shop/templates/utils.html
tests/test_functional.py

Render root and footer nav

---

shop/static/js/address-form.js
shop/templates/users/address-edit.html
shop/templates/users/addresses.html
shop/user/forms.py
shop/user/models.py
shop/user/views.py

Users can now edit existing addresses

---

manage.py
shop/app.py
shop/cart/forms.py
shop/cart/models.py
shop/cart/views.py
shop/checkout/forms.py
shop/checkout/models.py
shop/checkout/views.py
shop/cms/models.py
shop/cms/views.py
shop/filters.py
shop/fulfilio.py
shop/node/models.py
shop/node/views.py
shop/product/models.py
shop/product/views.py
shop/public/forms.py
shop/public/models.py
shop/public/views.py
shop/templates/checkout/payment.html
shop/user/forms.py
shop/user/models.py
shop/user/views.py
tests/conftest.py
tests/factories.py
tests/test_functional.py
tests/test_models.py

Store credit cards for future use securely

---

shop/app.py
shop/cms/views.py
shop/node/models.py
shop/product/models.py
shop/static/css/style.css
shop/templates/cms/category.html
shop/templates/cms/page.html
shop/templates/layout.html
shop/templates/node/node.html
shop/templates/product/product.html

@tarunbhardwaj Please review and merge [#130907181]

Render breadcrumb on shop

---

shop/cart/models.py
shop/checkout/views.py
shop/user/models.py
tests/test_functional.py

When user is logged in, transfer all the items to his cart

---

shop/templates/layout-my-account.html
shop/templates/partials/my-account-menu.html
shop/templates/users/orders.html

@tarunbhardwaj Please review [#126385001]

Buy again option in orders history

---

shop/checkout/views.py
shop/signals.py

Add cart user changed signal

---

shop/app.py
shop/cart/models.py
shop/globals.py
shop/product/models.py
shop/public/models.py
shop/templates/cart/cart.html
shop/templates/cart/order-confirmation.html
shop/templates/node/node.html
shop/templates/product/product.html

@prakashpp Please review [#130647511]

Currency formatting using MoneyType

---

shop/app.py

Language can be null in context, fix fallback en_US

Fix current_locale if language is null

---

shop/templates/users/addresses.html
shop/user/views.py

Adds ability to delete addresses

---

shop/templates/layout-my-account.html
shop/templates/users/account.html
shop/templates/users/orders.html
shop/user/forms.py
shop/user/views.py

Add account page

---

shop/user/forms.py
shop/user/models.py
shop/user/views.py

Add party field to contact mechanism[#131505605]

---

shop/templates/node/node.html
shop/templates/utils.html

Respect node grouping based on template[#131316173]

---

shop/cart/views.py

Update cart overlay using ajax

---

shop/public/views.py

Registering now redirects to login

---

shop/cart/forms.py
shop/cart/models.py
shop/cart/views.py

Use delivery_date instead of shipping_date

---

shop/cart/forms.py
shop/product/models.py

Use rpc method to fetch images url the media

---

shop/templates/emails/reset-password.html
shop/templates/emails/reset-password.text
shop/templates/public/reset-password-sent.html

Fixes for reset password

---

shop/cart/models.py

[#131801481]
@prakashpp Please review

Add gift message field to sale line model

---

shop/cart/views.py

Deleting item via xhr should not redirect to cart view

---

shop/cms/models.py
shop/cms/views.py

Admins should be able to submit a sitemap of articles

---

shop/cms/views.py
shop/templates/cms/sitemap.xml

Move sitemap.xml to cms

---

shop/cms/models.py
shop/filters.py
shop/node/models.py
shop/node/views.py
shop/templates/node/sitemap.xml

Adds sitemap for product tree nodes

---

shop/cms/views.py
shop/public/views.py
shop/templates/public/sitemap-index.xml

Add root sitemap which links all other (articles, nodes etc) sitemaps

---

shop/public/views.py
shop/templates/shop.js

Provision to submit login form from ajax

---

shop/user/forms.py
shop/user/models.py
shop/user/views.py

As a user, I should be edit/complete/correct address from shipping page

---

shop/user/views.py

Send full address as json while editing addresses

---

shop/checkout/views.py

As a user, I should be able to edit my billing address

---

shop/templates/users/orders.html
shop/user/views.py

Adds an filter_by option `open`, to filter user's orders by `processing` state

---

shop/user/models.py

Replace validation boolean with stringtype

---

shop/templates/shop.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/98)

Take event as argument for onSubmit of ajaxSubmit

---

shop/cart/models.py

[#132994255]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/100)

Add total_shipment_cost field to Sale

---

shop/product/models.py
shop/templates/shop.js

[#133009181]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/99)

Handle case when no listing for slug

---

shop/user/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/101)

Fix typo in order detail route

---

shop/cms/models.py
shop/node/models.py
shop/product/models.py
shop/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/103)

Expire cache in 10 mins

---

shop/cart/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/102)

Add a is_shipping_line flag to view_cart xhr response

---

shop/cart/views.py
shop/templates/shop.js
shop/user/views.py

[#131935593]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/106)

Add data required to refresh cart via xhr and don't redirect on xhr calls

---

shop/product/models.py
shop/settings.py
shop/utils.py

[#133341607]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/105)

Add provision to use imgix cdn

---

shop/node/models.py

Fixes: https://sentry.fulfil.io/fulfilio/fulfil-shop/group/4983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/108)

Type cast to int retrevied value from cache

---

shop/app.py
shop/node/models.py
shop/node/views.py
shop/product/models.py
shop/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/109)

Node page improvements

---

shop/settings.py
shop/templates/layout.html
shop/templates/partials/google-tag-manager.html

Add env var for GOOGLE_TAG_MANAGER
[#133432565]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/110)

Add provision to use google tag manager

---

shop/cart/models.py
shop/checkout/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/111)

Add a function to make sure sale is ready for payment

---

shop/cart/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/112)

Add cart sanitise method

---

shop/cart/models.py
shop/checkout/models.py
shop/checkout/views.py
shop/user/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/114)

Improvements on cart and address

---

shop/cart/models.py
shop/checkout/views.py
shop/templates/shop.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/116)

Add js functions for creating charging card

---

shop/app.py
shop/filters.py
shop/settings.py
shop/utils.py

[#133518141]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/115)

Add provision to cdnify url

---

.gitignore
requirements/dev.txt
shop/checkout/views.py
shop/public/models.py
shop/public/views.py
shop/static/js/address-form.js
shop/user/forms.py
shop/user/views.py
tests/conftest.py
tests/test_forms.py
tests/test_models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/117)

Implement Address form with country/state codes

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/118)

Don't bower anymore

---

shop/settings.py
shop/templates/layout.html
shop/user/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/121)

Add method to serialize an Address

---

shop/user/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/122)

Use serialize for address xhr response

---

shop/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/125)

Cache files in production for 24 hours

---

shop/cart/models.py
shop/cart/views.py
shop/templates/shop.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/123)

Provision to apply promo code

---

shop/templates/shop.js

[#133664437]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/127)

Do not blowup if google maps api not available

---

shop/user/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/129)

Add provision to save validation status of an address

---

shop/checkout/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/128)

Fix billing address route

---

shop/cart/views.py

* Handle XHR in cart routes
* Flash message should only be visible for non xhr request
[#133702169]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/130)

Handle xhr in cart routes

---

shop/product/models.py
shop/user/models.py
tests/test_models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/132)

Rapid fire improvements

---

shop/cart/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/120)

Cart size should not sum shipping line quantity

---

shop/contrib/klaviyo.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/133)

Add contrib module: klavio

---

shop/user/views.py

[#133585495]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/124)

Add xhr response to create address

---

shop/contrib/klaviyo.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/134)

Fix klaviyo contrib for product url

---

shop/product/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/135)

Allow listing url to be generated for external system

---

shop/templates/shop.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/136)

Do not merge street and street_number with comma

---

shop/utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/138)

Fix util method url_for_other_page used in pagination

---

shop/product/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/139)

Add a future option for brand

---

shop/user/views.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/141)

Show order in confirmed state for open

---

requirements/dev.txt
shop/cart/models.py
shop/contrib/ga.py
shop/product/models.py
shop/templates/partials/google-tag-manager.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/143)

Bunch of changes

---

manage.py
requirements/prod.txt
shop/app.py
shop/extensions.py
shop/jobs.py
shop/product/models.py
shop/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/144)

Warm the cache

---

shop/public/models.py
shop/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/145)

More caching

---

shop/templates/shop.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/146)

Address lookup correction

---

setup.py
shop/app.py
shop/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/147)

Added support for new-relic

---

shop/cart/forms.py

[#133824037]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/148)

Add validator to check for non-negative quantity

---

shop/contrib/klaviyo.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/149)

Handle case when listing is not there for product

---

shop/contrib/ga.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/150)

Use SKU for reporting GA metrics

---

shop/user/forms.py
shop/user/views.py
tests/test_forms.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/151)

Add conditional required on address fields

---

shop/cart/models.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/152)

Fix cart search

---

shop/checkout/views.py

When the tokenized card is converted to payment profile
some aspects of the card like the CVV are validated. So
this could fail at this point and when that happens, no
error messages reach the user.
This patch handles the error, uses 402 (Payment Required)
error response which the client can then handle.
Fixes: https://sentry.fulfil.io/fulfilio/fulfil-shop/group/5170/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/153)

Pass card creation errors back to user

---

shop/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fulfilio/shop/154)

Show email and name on sentry
